import express from "express";
import rateLimit from "express-rate-limit";
import { adminAuth, requirePermission, requireRole } from "../middleware/adminAuth.js";
import * as admin from "../controller/adminController.js";
import sahyogRouter from "./sahyogRoute.js";

const router = express.Router();
const loginLimiter = rateLimit({ windowMs: 15 * 60 * 1000, limit: 10, standardHeaders: true, legacyHeaders: false, message: { success: false, message: "Too many login attempts. Try again later." } });
router.post("/auth/login", loginLimiter, admin.loginAdmin);
router.use(adminAuth);
router.get("/auth/me", admin.getAdminMe);
router.get("/dashboard", admin.dashboard);
router.get("/activity", requireRole("superadmin"), admin.listActivity);
router.get("/admins", requireRole("superadmin"), admin.listAdmins);
router.post("/admins", requireRole("superadmin"), admin.createAdmin);
router.patch("/admins/:id", requireRole("superadmin"), admin.updateAdmin);
router.patch("/admins/:id/status", requireRole("superadmin"), admin.setAdminStatus);
router.post("/admins/:id/reset-password", requireRole("superadmin"), admin.resetAdminPassword);
router.get("/admins/:id/rights", requireRole("superadmin"), admin.getRights);
router.put("/admins/:id/rights", requireRole("superadmin"), admin.updateRights);
router.get("/members", requirePermission("members", "view"), admin.listManagedMembers);
router.post("/members", requirePermission("members", "create"), admin.createManagedMember);
router.patch("/members/:id", requirePermission("members", "update"), admin.updateManagedMember);
router.delete("/members/:id", requirePermission("members", "delete"), admin.deleteManagedMember);
router.get("/referrals", requirePermission("referrals", "view"), admin.listReferrals);
router.post("/referrals", requirePermission("referrals", "create"), admin.createReferral);
router.patch("/referrals/:id", requirePermission("referrals", "update"), admin.updateReferral);
router.delete("/referrals/:id", requirePermission("referrals", "delete"), admin.deleteReferral);
router.use("/", sahyogRouter);
export default router;
