import { useCallback, useEffect, useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { toast } from "react-toastify";
import { adminApi } from "../../services/adminApi.js";
import { LoadingButton, PageHeading, StatusBadge } from "./SahyogUi.jsx";

const money = (amount) => `₹${Number(amount || 0).toLocaleString("en-IN")}`;
const can = (admin, action) => admin.role === "superadmin" || admin.permissions?.some((item) => item.module === "sahyog-donations" && item.actions.includes(action));

export default function SahyogDonations({ token, admin, root }) {
  const { id } = useParams(); const navigate = useNavigate();
  const [donations, setDonations] = useState([]); const [caseItem, setCaseItem] = useState(null); const [isLoading, setIsLoading] = useState(true); const [changingId, setChangingId] = useState(null);
  const load = useCallback(async () => { setIsLoading(true); try { const [donationsResponse, caseResponse] = await Promise.all([adminApi(token).get(`/sahyog/${id}/donations`), adminApi(token).get(`/sahyog/${id}`)]); setDonations(donationsResponse.data.donations || []); setCaseItem(caseResponse.data.sahyog); } catch (error) { toast.error(error.response?.data?.message || "Could not load donor details"); } finally { setIsLoading(false); } }, [id, token]);
  useEffect(() => { load(); }, [load]);
  const summary = useMemo(() => donations.filter((item) => item.paymentStatus === "success").reduce((value, item) => ({ amount: value.amount + Number(item.amount || 0), count: value.count + 1 }), { amount: 0, count: 0 }), [donations]);
  const changeStatus = async (donationId, action) => { const isReject = action === "reject"; if (!window.confirm(`${isReject ? "Reject" : "Verify"} this donation?`)) return; setChangingId(donationId); try { await adminApi(token).patch(`/sahyog/${id}/donations/${donationId}/${action}`); toast.success(isReject ? "Donation rejected" : "Donation verified"); await load(); } catch (error) { toast.error(error.response?.data?.message || `Could not ${action} donation`); } finally { setChangingId(null); } };
  return <><PageHeading title="Donors and donations" subtitle="Only verified donations are included in the total." action={<button onClick={() => navigate(`${root}/sahyog`)} className="rounded-lg border px-4 py-2 text-sm font-semibold">Back to cases</button>} />{isLoading ? <p className="py-12 text-center text-slate-500">Loading donors…</p> : <><section className="mb-6 grid gap-4 md:grid-cols-3"><div className="rounded-xl border bg-white p-5"><p className="text-sm text-slate-500">Member</p><p className="mt-1 font-bold text-[#5a0615]">{caseItem?.memberId?.fullName || "Member"}</p><p className="mt-1 text-sm text-slate-500">{caseItem?.memberId?.memberId || "—"}</p></div><div className="rounded-xl border bg-emerald-50 p-5"><p className="text-sm text-emerald-800">Total donation</p><p className="mt-1 text-2xl font-bold text-emerald-950">{money(summary.amount)}</p><p className="mt-1 text-sm text-emerald-800">{summary.count} verified donor{summary.count === 1 ? "" : "s"}</p></div><div className="rounded-xl border bg-white p-5"><p className="text-sm text-slate-500">Case details</p><p className="mt-1 font-semibold">Target: {caseItem?.targetAmount ? money(caseItem.targetAmount) : "Not set"}</p><p className="mt-1 text-sm text-slate-500">Total submissions: {donations.length}</p></div></section><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{donations.map((donation) => <article key={donation._id} className="rounded-xl border bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold text-[#5a0615]">{donation.isAnonymous ? "Anonymous" : donation.donorId?.fullName || donation.donorName || "—"}</h3><p className="mt-1 text-sm text-slate-500">{donation.donorId?.memberId || donation.donorMobile || "Guest donor"}</p></div><StatusBadge value={donation.paymentStatus} /></div><p className="mt-4 text-xl font-bold">{money(donation.amount)}</p><p className="mt-2 text-sm text-slate-500">{donation.paymentMethod || "Payment method unavailable"} · {donation.transactionId || "No transaction ID"}</p><p className="mt-2 text-xs text-slate-500">Submitted {new Date(donation.createdAt).toLocaleString("en-IN")}</p><div className="mt-4 flex flex-wrap gap-3">{can(admin, "verify") && donation.paymentStatus !== "success" && <LoadingButton loading={changingId === donation._id} onClick={() => changeStatus(donation._id, "verify")} className="font-semibold text-[#78081c]">Verify donation</LoadingButton>}{can(admin, "reject") && donation.paymentStatus !== "rejected" && <LoadingButton loading={changingId === donation._id} onClick={() => changeStatus(donation._id, "reject")} className="font-semibold text-rose-700">Reject donation</LoadingButton>}</div></article>)}</div>{!donations.length && <p className="rounded-xl border bg-white p-8 text-center text-slate-500">No donations recorded.</p>}</>}</>;
}
